export const COPY = {
  brand: {
    appName: 'Fold Vote',
    documentTitle: 'Fold Vote - DAVINCI',
    poweredBy: 'Powered by',
    madeWith: 'Made with',
    by: 'by',
    davinciLogoAlt: 'Davinci logo',
    vocdoniLogoAlt: 'Vocdoni logo',
  },
  app: {
    routeLoading: 'Loading...',
  },
  shared: {
    create: 'Create',
    explore: 'Explore',
    copy: 'Copy',
    copied: 'Copied!',
    retry: 'Retry',
    error: 'Error',
    close: 'Close',
    loading: 'Loading...',
    unknown: 'Unknown',
  },
  home: {
    eyebrow: 'Wallet-based anonymous voting',
    title: 'Create a vote. Connect your wallet. Cast your ballot.',
    intro:
      'Launch elections where participants vote with their Ethereum wallet. Results are tallied through the DAVINCI Fold proving pipeline: transparent, auditable, and private.',
    primaryCta: 'Create an election',
    secondaryCta: 'Explore elections',
    howItWorks: {
      eyebrow: 'How it works',
      title: 'From wallet to result in three steps.',
      steps: [
        {
          title: 'Create the election',
          description: 'Define the question, options, eligible addresses, and duration.',
        },
        {
          title: 'Share the vote link',
          description: 'Send the URL to eligible participants. They connect their wallet and vote.',
        },
        {
          title: 'Collect the results',
          description: 'Results are proven via ZK fold proofs — transparent and tamper-evident.',
        },
      ],
    },
  },
  create: {
    headerTitle: 'Create a voting election',
    headerIntro:
      'Define the question, add vote options, paste the list of eligible Ethereum addresses, and set a deadline.',
    walletPrompt: 'Connect your wallet to create an election.',
    walletConnecting: 'Connecting wallet...',
    walletFailedConnect: 'Failed to connect wallet.',
    form: {
      titleLabel: 'Election title',
      titlePlaceholder: 'What is your question?',
      descriptionLabel: 'Description (optional)',
      descriptionPlaceholder: 'Provide more context for voters...',
      optionsTitle: 'Vote options',
      optionPlaceholder: (i: number) => `Option ${i + 1}`,
      addOption: '+ Add option',
      removeOption: 'Remove',
      addressesLabel: 'Eligible addresses',
      addressesPlaceholder:
        '0xabc…\n0xdef…\n\nOne address per line, or comma-separated.',
      addressesHelper: 'Only these addresses will be allowed to vote.',
      endTimeLabel: 'Election end time',
      endTimeHelper: 'UTC — leave blank for no deadline.',
      createButton: 'Create election',
      creatingButton: 'Creating...',
    },
    pipeline: {
      validateForm: 'Validate form',
      connectWallet: 'Connect wallet',
      buildCensus: 'Build census',
      generateKeypair: 'Generate encryption keypair',
      createElection: 'Create election on fold backend',
      done: 'Done',
    },
    success: {
      title: 'Election created!',
      shareLinkLabel: 'Share this link with eligible voters',
      copyLinkTitle: 'Copy vote link',
    },
    errors: {
      missingTitle: 'Election title is required.',
      missingOptions: 'At least 2 vote options are required.',
      duplicateOptions: 'Vote options must be unique.',
      missingAddresses: 'At least one eligible address is required.',
      invalidAddress: (addr: string) => `Invalid Ethereum address: ${addr}`,
      missingFoldUrl: 'VITE_DAVINCI_FOLD_URL is not set.',
      missingAdminJwt: 'VITE_ADMIN_JWT is not set.',
      createFailed: 'Failed to create election.',
    },
  },
  vote: {
    headerLoadingTitle: 'Loading election...',
    missingId: 'Open a /vote/:electionId link to see this election.',
    invalidId: 'Invalid election ID in URL.',
    notFound: 'Election not found.',
    connectPrompt: 'Connect your wallet to vote.',
    connectingWallet: 'Connecting wallet...',
    notEligible: 'Your wallet address is not in the census for this election.',
    alreadyVoted: 'You have already voted in this election.',
    selectOption: 'Select one option before submitting.',
    submitButton: 'Submit vote',
    submittingButton: 'Submitting...',
    voteSubmitted: 'Vote submitted!',
    voteError: 'Vote submission failed.',
    closedStatuses: {
      ended: 'This election has ended. Voting is closed.',
      decrypting: 'This election has ended and results are being decrypted.',
      finalizing: 'Results are being finalized.',
      results: 'Results are available. Voting is closed.',
      paused: 'This election is paused.',
      canceled: 'This election was canceled.',
      created: 'This election has not started yet.',
    },
    lifecycle: {
      active: 'Active',
      ended: 'Ended',
      decrypting: 'Decrypting',
      finalizing: 'Finalizing',
      results: 'Results available',
      paused: 'Paused',
      canceled: 'Canceled',
    },
    voteStatus: {
      pending: { label: 'Pending', description: 'Vote received and queued.' },
      batched: { label: 'Batched', description: 'Assigned to a batch being proved.' },
      folded: { label: 'Folded', description: 'Batch STARK proved and folded into chain.' },
      settled: { label: 'Settled', description: 'Vote fully settled in final proof.' },
      error: { label: 'Error', description: 'Vote processing failed.' },
    },
    results: {
      title: 'Election Results',
      totalVotes: 'Total votes',
      noMetadata: 'No question metadata found. Showing raw tally.',
    },
  },
  explore: {
    headerTitle: 'Explore elections',
    headerIntro: 'Browse all elections running on this fold backend.',
    loading: 'Loading elections...',
    loadingFailed: 'Failed to load elections.',
    empty: 'No elections found.',
    retry: 'Retry',
    filterAll: 'All',
    filterActive: 'Active',
    filterResults: 'Results',
  },
  navbar: {
    home: 'Fold Vote',
    create: 'Create',
    explore: 'Explore',
    walletTitle: 'Wallet',
    disconnected: 'Not connected',
    disconnect: 'Disconnect',
  },
} as const;
