source "https://rubygems.org"

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.2"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem "cocoapods", ">= 1.13", "!= 1.15.0", "!= 1.15.1"
gem "activesupport", ">= 6.1.7.5", "!= 7.1.0"

# Add fastlane for CI/CD
gem "fastlane", "~> 2.230.0"

group :development do
  gem "dotenv"
  gem "nokogiri", "~> 1.18", platform: :ruby
end

plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
