export const COPY = {
  brand: {
    appName: 'Ask The World',
    documentTitle: 'Ask The World - DAVINCI',
    poweredBy: 'Powered by',
    and: 'and',
    madeWith: 'Made with',
    by: 'by',
    joinVoteShare: 'Join this vote on Ask The World - DAVINCI',
    davinciLogoAlt: 'Davinci logo',
    selfLogoAlt: 'Self logo',
    vocdoniLogoAlt: 'Vocdoni logo',
  },
  popup: {
    closePopup: 'Close popup',
    modalBackdrop: 'Modal backdrop',
  },
  app: {
    routeLoading: 'Loading route...',
  },
  support: {
    eyebrow: 'Support',
    title: 'Need help?',
    description: 'Questions or problems? Get in touch with the Vocdoni team and we’ll help you out.',
    discord: 'Discord',
    telegram: 'Telegram',
    dismiss: 'Dismiss support popup',
  },
  shared: {
    explore: 'Explore',
    copy: 'Copy',
    copied: 'Copied',
    retry: 'Retry',
    error: 'Error',
    close: 'Close',
    unknown: 'Unknown',
    hidden: 'hidden',
    pending: 'Pending',
    running: 'Running',
    completed: 'Completed',
    resultsPending: 'Computing results',
    advancedDetails: 'Advanced Details',
  },
  createConstants: {
    eligibilityTooltip:
      'You set the eligibility rules here. Anyone with a modern ID or Passport from most countries can securely vote, as long as they meet your criteria (Countries & Age) and participate during the process duration.',
  },
  create: {
    walletStatusDefault:
      'Connect MetaMask or another browser wallet. WalletConnect is used when no extension wallet is detected.',
    missingWalletConnectHint: 'VITE_WALLETCONNECT_PROJECT_ID (needed when no browser extension wallet is detected)',
    connectingWallet: 'Connecting browser wallet...',
    failedConnectWallet: 'Failed to connect creator wallet.',
    walletBalanceChecking: 'Checking CELO balance...',
    walletNeedsFundsBeforeCreate:
      "Almost there! Creating a vote requires a tiny bit of CELO for transaction fees. Don't have any? No worries, get some for free",
    walletFaucetLabel: 'here',
    walletFaucetUrl: 'https://stakely.io/faucet/celo-celo',
    walletConnectPromptLead: 'Connect your wallet. Every vote you create counts, and',
    walletConnectPromptEmphasis: "early builders won't go unnoticed",
    shareSocialText: 'Join this vote on Ask The World - DAVINCI',
    navbar: {
      walletTitle: 'Creator Wallet',
      disconnected: 'Disconnected',
      disconnect: 'Disconnect',
      connectWalletToCreate: 'Connect wallet to create',
      connectWalletSource: (sourceLabel: string, networkLabel: string) =>
        `Connected with ${sourceLabel} on ${networkLabel}.`,
    },
    header: {
      title: 'What do you want to ask?',
      introParagraph1: 'Ask any question, target any country or groups.',
      introParagraph2BeforeSelf: "Citizens prove they're real with their ID or passport using",
      introParagraph2BetweenLinks: ', and vote in complete anonymity through the',
      introParagraph3: 'No data exposed. No double votes. No coercion.',
      introParagraph4: 'Just truth, verified on-chain.',
    },
    form: {
      processPlaceholder: 'Type your question here...',
      optionsTitle: 'The options',
      optionPlaceholder: (index: number) => `Option ${index + 1}`,
      removeOptionTitle: 'Remove',
      addOption: '+ Add a new option',
      eligibilityTitle: 'Who can vote and for how long?',
      eligibilityInfoAria: 'Eligibility information',
      countryCardTitle: 'Select up to five countries allowed to vote',
      countryLabel: 'Country',
      selectedCountriesHelper: (selected: number, max: number) =>
        `Select up to ${max} countries (${selected}/${max})`,
      removeCountryAria: (countryLabel: string) => `Remove ${countryLabel}`,
      chooseCountriesAria: 'Choose allowed countries',
      countrySearchPlaceholder: 'Type to search countries...',
      allowedCountriesAria: 'Allowed countries',
      noCountriesFound: 'No countries found',
      minAgeCardTitle: 'Minimum age required to vote',
      minAgeLabel: 'Minimum age to vote',
      decreaseMinAge: 'Decrease minimum age',
      increaseMinAge: 'Increase minimum age',
      durationCardTitle: 'How long the voting process will remain open',
      durationLabel: 'Vote duration',
      decreaseDuration: 'Decrease vote duration',
      increaseDuration: 'Increase vote duration',
      decreaseDurationDays: 'Decrease vote duration days',
      increaseDurationDays: 'Increase vote duration days',
      durationDaysUnit: 'Days',
      durationUnit: 'Hours',
      advancedSettings: '▾ Advanced Settings',
      maxVotersLabel: 'Maximum voters',
      maxVotersHelper: 'Limit the number of participants.',
      listInExploreLabel: 'Show in Explore',
      listInExploreHelper: 'Turn this off for private or testing processes.',
      createButton: 'Create the voting process',
      creatingButton: 'Creating process...',
    },
    overlay: {
      successTitle: 'Process created',
      loadingTitle: 'Creating process...',
      statusTitle: 'Process creation status',
      closeLabel: 'Close creation popup',
      walletKeepOpen:
        'Keep your wallet open. You will be prompted to confirm transactions and sign messages during setup.',
      copyLink: 'Copy link',
    },
    success: {
      title: 'Your voting process is live and ready for the world.',
      shareLinkLabel: 'Share this link to start collecting votes',
      copyLinkTitle: 'Copy link',
      shareSocialLabel: 'Share on social networks',
      shareAria: (label: string) => `Share on ${label}`,
    },
    outputs: {
      censusContract: 'Census contract',
      deploymentTx: 'Deployment tx',
      censusUri: 'Census URI',
      processId: 'Process ID',
      processTx: 'Process tx',
    },
    status: {
      internalWalletRpcRetry: (attempt: number, maxAttempts: number) =>
        `Internal wallet RPC error. Retrying (${attempt}/${maxAttempts})...`,
      stageFailed: (stageLabel: string) => `Could not complete "${stageLabel}". Check browser console for technical details.`,
      indexerAcceptedContract: 'Indexer accepted contract',
      censusEndpointReady: 'Census query endpoint is ready',
      graphQlReturnedErrors: 'GraphQL returned errors',
      indexerReadinessFailed: 'Indexer readiness failed',
      processReadyInSequencer: 'Process is ready in sequencer',
      processNotAcceptingVotesYet: 'Process is not accepting votes yet',
      sequencerLookupFailed: 'Sequencer lookup failed',
      formValidated: 'Form validated',
    },
    errors: {
      missingWalletContextSelfConfig: 'Missing wallet context for Self config registration.',
      missingWalletContextDeployment: 'Missing wallet context for contract deployment.',
      missingContractAddress: 'Contract address was not found in deployment receipt.',
      missingIndexerUrl: 'Missing VITE_ONCHAIN_CENSUS_INDEXER_URL.',
      missingProcessValuesIndexer: 'Missing process values for indexer bootstrap.',
      missingSequencerUrl: 'Missing VITE_DAVINCI_SEQUENCER_URL.',
      missingSignerOrValues: 'Missing signer or process values for sequencer process creation.',
      missingCensusUri: 'Missing census URI for sequencer process creation.',
      missingProcessId: 'Process creation did not return a process ID.',
    },
  },
  explore: {
    loadingError: 'Failed to load processes from sequencer.',
    missingSequencerUrl: 'Missing VITE_DAVINCI_SEQUENCER_URL.',
    headerTitle: 'Explore processes',
    headerTextBeforeSelf:
      'Browse processes created with this app. The list only includes voting processes compatible with',
    headerTextAfterSelf: 'identification flow and links directly to each voting page.',
    statsShowing: (count: number) => `Showing ${count} compatible process${count === 1 ? '' : 'es'}`,
    retry: 'Retry',
    loading: 'Loading processes...',
    emptyState: 'No compatible processes found.',
    requirementsPrefix: 'Countries:',
    requirementsMinAge: 'Minimum age:',
    requirementsClosesIn: 'Closes in:',
    loadingMore: 'Loading...',
    loadMore: 'Load more',
  },
  vote: {
    closedProcess: {
      results: 'This process is in results stage. Registration and voting are closed.',
      ended: 'This process has ended. Registration and voting are closed.',
      paused: 'This process is paused. Registration and voting are closed.',
      canceled: 'This process was canceled. Registration and voting are closed.',
      notAccepting: 'This process is not accepting votes yet.',
    },
    lifecycle: {
      defaultTitle: 'Vote Active',
      defaultLabel: 'Active',
      defaultDescription: 'Voting is open while this process remains active.',
      pendingTitle: 'Vote Pending',
      notStartedLabel: 'Not started',
      endedTitle: 'Vote Ended',
      endedLabel: 'Ended',
      endedDescription: 'Voting time has ended. Registration and voting are closed.',
    },
    context: {
      invalidProcessId:
        'A valid process ID is required to use this app. Please request the complete /vote/:processId link from the person or team that shared this app.',
      requiredToContinue: 'A valid /vote/:processId link is required to continue.',
      missingInUrl: 'Missing process ID in URL. Open the complete /vote/:processId link shared for this process.',
      invalidInUrl: 'Invalid process ID in URL. Open a valid /vote/:processId link to use this app.',
      popupTitle: 'This voting link is incomplete',
      popupClose: 'Close context popup',
      popupEyebrow: 'Process ID required',
    },
    status: {
      resolveProcessAndWallet: 'Resolve process and managed wallet before generating Self QR.',
      loadingQuestion: 'Loading process question...',
      noQuestionFound: 'No vote question was found in this process.',
      oneQuestionOnly: 'This app supports one question only. Showing the first question.',
      failedLoadQuestion: 'Failed to load process question.',
      alreadyVotedOverwrite:
        'This identity wallet already has a vote in sequencer. You can submit again to overwrite it.',
      enterProcessId: 'Enter a process ID to resolve it.',
      resolvingProcess: 'Resolving process...',
      resolvingFromSequencer: 'Resolving process from sequencer...',
      processResolved: 'Process resolved. Readiness checks are active.',
      failedResolveProcess: 'Failed to resolve process.',
      scopeSeedRequired: 'Scope seed is required to generate Self QR.',
      scopeSeedAscii: 'Scope seed must be ASCII and up to 31 characters.',
      generatingSelfQr: 'Generating Self QR...',
      selfQrReady: 'Self QR ready. Complete verification in Self and wait for readiness to turn Yes.',
      failedGenerateSelfQr: 'Failed to generate Self QR.',
      selfLinkCopied: 'Self link copied to clipboard.',
      failedCopySelfLink: 'Failed to copy Self link.',
      resolveBeforeSubmit: 'Resolve process and managed wallet before submitting vote.',
      registrationPendingBoth:
        'Registration still pending. Wait until Onchain and Sequencer readiness are both Yes.',
      registrationPendingSequencer: 'Registration still pending. Wait until Sequencer readiness is Yes.',
      voteInProgressOverwrite:
        'Current vote is still processing. Wait until status becomes Settled or Error before overwriting.',
      noQuestionAvailable: 'No question available for this process.',
      selectOneOption: 'Select one option before submitting.',
      missingCensusConfig: 'Missing census URL config for vote proof generation.',
      connectingBrowserWallet: 'Connecting browser wallet...',
      browserWalletConnected: (sourceLabel: string) =>
        sourceLabel ? `Browser wallet connected with ${sourceLabel}.` : 'Browser wallet connected.',
      failedConnectBrowserWallet: 'Failed to connect browser wallet.',
      browserWalletSignerRequired: 'Reconnect your browser wallet before submitting this vote.',
      pausingProcess: 'Pausing process...',
      processPaused: 'Process paused.',
      failedPauseProcess: 'Failed to pause process.',
      pauseProcessTimeout: 'Pause transaction was sent, but the process did not reach paused status within 35 seconds.',
      resumingProcess: 'Resuming process...',
      processResumed: 'Process resumed.',
      failedResumeProcess: 'Failed to resume process.',
      resumeProcessTimeout: 'Resume transaction was sent, but the process did not reach active status within 35 seconds.',
      stoppingProcess: 'Stopping process and starting results computation...',
      processStopped: 'Process stopped. Results are being calculated.',
      failedStopProcess: 'Failed to stop process.',
      stopProcessTimeout: 'Stop transaction was sent, but the process did not reach ended status within 35 seconds.',
      submittingVote: 'Submitting vote...',
      invalidOptionForQuestion: 'Selected option is not valid for this vote question.',
      voteSubmitted: 'Vote submitted successfully.',
      failedSubmitVote: 'Failed to submit vote.',
      registrationRequired: 'Registration required. Complete Self verification and your vote will submit automatically.',
      registrationProcessChanged:
        'Process changed while registration was pending. Submit vote again for this process.',
      registrationWalletChanged: 'Managed wallet changed while registration was pending. Submit vote again.',
      autoSubmitFailed:
        'Vote was not submitted after registration. Review the error and click submit vote again.',
      popupClosed: 'Registration popup closed. Click submit vote again when you are ready.',
      selfVerificationCompleted: 'Self verification completed. Waiting for onchain/sequencer readiness.',
      selfVerificationFailed: 'Self verification failed.',
      selfQrError: (reason: string) => (reason ? `Self QR error: ${reason}` : 'Self verification failed.'),
      voteStatusUpdate: (statusLabel: string) => `Vote submitted. Current status: ${statusLabel}.`,
    },
    buttons: {
      submittingVote: 'Submitting vote...',
      votingClosed: 'Voting closed',
      votingPaused: 'Voting paused',
      waitingForRegistration: 'Waiting for registration...',
      submitVoteAgain: 'Submit vote again',
      voteInProgress: 'Vote in progress',
      submitVote: 'Submit vote',
      details: 'Details',
      identity: 'Identity',
      copyPrivateKey: 'Copy private key',
      importKey: 'Import private key',
      confirmImport: 'Confirm import',
      connectBrowserWallet: 'Connect browser wallet',
      connectingBrowserWallet: 'Connecting wallet...',
      useLocalDerivedWallet: 'Use local derived wallet',
      pauseProcess: 'Pause process',
      pausingProcess: 'Pausing...',
      resumeProcess: 'Resume process',
      resumingProcess: 'Resuming...',
      stopProcess: 'Stop process',
      stoppingProcess: 'Stopping...',
      copyLink: 'Copy link',
      openInSelfApp: 'Open in Self app',
    },
    header: {
      loadingQuestion: 'Loading question...',
      chooseOption: 'Choose an option',
      resultsAvailable: 'Results are available for this process.',
      helpBeforeSelf: 'Choose an option, join the census through the',
      helpAfterSelf: 'app, and cast your vote.',
    },
    dialogs: {
      processDetailsTitle: 'Process Details',
      processDetailsClose: 'Close process details popup',
      managedIdentityTitle: 'Identity Wallet',
      managedIdentityClose: 'Close identity popup',
      identityIntroPrimary:
        'We set up an ephemeral identity for you: no wallet or setup needed. It\'s tied to this browser, so clearing data or switching devices means starting fresh.',
      identityIntroSecondary:
        'Want to use your own identity? Connect your wallet instead. Early users won\'t be forgotten. Your votes stay fully anonymous regardless.',
      importBeforeProcess: 'Open /vote/:processId before importing a key.',
      connectBeforeProcess: 'Open /vote/:processId before connecting a browser wallet.',
      resetBeforeProcess: 'Open /vote/:processId before resetting key.',
      importedKeyApplied: 'Imported key applied for this process.',
      localWalletRestored: 'Local wallet restored for this process.',
      privateKeyFormatError: 'Private key must be 0x-prefixed 64 hex chars.',
      invalidPrivateKey: 'Invalid private key.',
      privateKeyCopied: 'Private key copied to clipboard.',
      failedCopyPrivateKey: 'Failed to copy private key.',
      warningKeyExposure: 'Anyone with this private key can reuse this voting identity for this process.',
      importPrivateKeyLabel: 'Paste private key',
      importPrivateKeyPlaceholder: '0xabc…',
      importPreviewAddress: 'Detected address',
      walletAddress: 'Address',
      walletSource: 'Source',
      walletSourceConnected: 'Connected',
      walletSourceDerived: 'Ephemeral Identity',
      walletSourceImported: 'Imported',
      walletSourceConnectedHelper: (sourceLabel: string) =>
        sourceLabel ? `Connected with ${sourceLabel}. This address will be used for registration and voting.` : 'Connected browser wallet. This address will be used for registration and voting.',
      walletSourceDerivedHelper: 'Created automatically on this device for this process.',
      walletSourceImportedHelper: 'Using a private key you imported for this process.',
      processId: 'Process ID',
      duration: 'Duration',
      censusContract: 'Census contract',
      censusUri: 'Census URI',
      sequencer: 'Sequencer',
      adminWidgetTitle: 'Admin Controls',
      adminWidgetDescription:
        'This connected wallet is the process creator. You can pause or resume voting here, or stop the process to trigger result computation.',
    },
    results: {
      summaryTitle: 'Vote Summary',
      totalVotes: 'Total votes',
      choicesWithVotes: 'Choices with votes',
      detailedResults: 'Detailed Results',
      totalLabel: (count: number) => `Total: ${count} vote${count === 1 ? '' : 's'}`,
      computing: 'Computing results',
      noMetadata: 'No question metadata available for this process.',
      ofTotalVotes: 'of total votes',
      rank: (rank: number) => `Rank #${rank}`,
    },
    ballot: {
      questionLegendFallback: 'Question',
      noQuestion: 'No question available for this process.',
      timeUntilClose: 'Time until close',
      trackVoteStatus: 'Track vote status',
      voteId: 'Vote ID',
    },
    submitResult: {
      receivedTitle: 'Vote successfully received',
      receivedDescription: 'Your vote is secured and being finalized.',
      finalizedTitle: 'Vote finalized successfully',
      finalizedDescription: 'Your vote has been fully settled.',
      failedTitle: 'Vote processing failed',
      failedDescription: 'Processing failed for this vote. Expand the panel for details and try again if needed.',
    },
    registration: {
      popupTitle: 'Complete Self verification to continue',
      popupClose: 'Close registration popup',
      popupEyebrow: 'Registration required',
      qrAria: 'Self registration QR code',
      preparingQr: 'Preparing Self QR...',
      copySelfLinkAria: 'Copy Self link',
      copySelfLinkTitle: 'Copy Self link',
      requirementsToVote: 'Requirements to vote',
      minimumAge: 'Minimum age',
      countries: 'Countries',
      quickSteps: 'Quick steps',
      openSelfApp: 'Open Self app',
      installSelfApp: 'Install Self app',
      mobileInstallHelpBeforeIos: 'Get it on',
      mobileInstallHelpBetween: 'or',
      desktopInstallHelpBeforeIos: 'Available on',
      desktopInstallHelpBetween: 'and',
      verifyMobile: 'Verify your ID or passport',
      verifyDesktop: 'Use a valid ID or passport',
      verifyMobileHelper: 'Complete verification in Self to join the census.',
      verifyDesktopHelper: 'Complete identity verification in Self to be added to the census.',
      finishMobile: 'Finish in Self and return here',
      finishDesktop: 'Finish this registration request',
      finishMobileHelper: 'Tap "Open in Self app" below and complete verification.',
      finishDesktopHelper: 'Scan the QR (or open the deep-link) and wait for readiness.',
      registrationProgress: 'Registration progress',
      registrationCompletedSubmitting: 'Registration completed. Your vote is being submitted...',
      identityPromptLead: 'Want to use your own identity?',
      identityPromptLink: 'Connect your wallet here.',
      identityPromptFootnote: "Early users won't be forgotten. Your vote stays anonymous.",
      progressSteps: {
        onchainLabel: 'Onchain census inclusion',
        onchainDescription: 'After Self verification, this step completes when onchain weight is greater than zero.',
        sequencerLabel: 'Sequencer census inclusion',
        sequencerDescription: 'This step completes when sequencer weight is greater than zero.',
        readyLabel: 'Ready to submit',
        readyDescription: 'Vote submission unlocks as soon as readiness checks pass.',
      },
    },
  },
  occ: {
    createHeaderTitle: 'Official-ID Voting Process Creator',
    voteHeaderTitle: 'Official-ID Voting Process',
    pipelineStages: {
      validateForm: 'Validate form',
      connectCreatorWallet: 'Connect creator browser wallet',
      ensureSelfConfigRegistered: 'Ensure Self config registered',
      deployCensusContract: 'Deploy census contract',
      startIndexer: 'Start indexer',
      waitIndexerReady: 'Wait indexer ready',
      createDavinciProcess: 'Create Davinci process',
      waitProcessReadyInSequencer: 'Wait process ready in sequencer',
      done: 'Done',
    },
    voteStatusInfo: {
      pending: {
        label: 'Pending',
        description: 'Vote was received and queued by the sequencer.',
      },
      verified: {
        label: 'Verified',
        description: 'Vote proof was verified correctly.',
      },
      aggregated: {
        label: 'Aggregated',
        description: 'Vote was merged into the current aggregation batch.',
      },
      processed: {
        label: 'Processed',
        description: 'Vote was processed and is ready for settlement.',
      },
      settled: {
        label: 'Settled',
        description: 'Vote was fully settled.',
      },
      error: {
        label: 'Error',
        description: 'Vote processing failed. Check the emit status message.',
      },
    },
    processStatusInfo: {
      ready: {
        label: 'Active',
        title: 'Vote Active',
        description: 'Voting is open while this process remains active.',
      },
      ended: {
        label: 'Ended',
        title: 'Vote Ended',
        description: 'Voting is closed. Results are not available yet.',
      },
      canceled: {
        label: 'Canceled',
        title: 'Vote Canceled',
        description: 'This process was canceled. Registration and voting are disabled.',
      },
      paused: {
        label: 'Paused',
        title: 'Vote Paused',
        description: 'This process is paused. Registration and voting are disabled.',
      },
      results: {
        label: 'Results',
        title: 'Vote Results',
        description: 'Results are available. Registration and voting are closed.',
      },
    },
    format: {
      ended: 'Ended',
      lessThanOneMinute: '<1m',
    },
    errors: {
      asciiField: (label: string) => `${label} accepts ASCII characters only. Check browser console for technical details.`,
      questionFallback: (index: number) => `Question ${index + 1}`,
      choiceFallback: (index: number) => `Choice ${index + 1}`,
      optionFallback: 'Option 1',
      invalidWeightAddress: 'Invalid address format for weightOf query.',
    },
  },
  walletService: {
    walletConnectFallbackSource: 'WalletConnect',
    metaMask: 'MetaMask',
    coinbaseWallet: 'Coinbase Wallet',
    browserWallet: 'Browser wallet',
    missingProjectId: 'Missing VITE_WALLETCONNECT_PROJECT_ID.',
    appDescription: 'Create and vote on census-based processes',
    noWalletAccount: 'No wallet account selected.',
  },
  readinessService: {
    rpcUnavailable: 'RPC unavailable for active network.',
    ethCallFailed: 'eth_call failed',
  },
} as const;
