[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
remappings = [
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/davinci-onchain-census-contract/lib/openzeppelin-contracts/",
  "poseidon-solidity/=lib/davinci-onchain-census-contract/lib/poseidon-solidity/contracts/",
  "zk-kit.solidity/=lib/davinci-onchain-census-contract/lib/zk-kit.solidity/",
  "@openzeppelin/contracts/=lib/davinci-onchain-census-contract/lib/openzeppelin-contracts/contracts/",
  "@selfxyz/contracts/=lib/self/contracts/",
  "davinci-contracts/=lib/davinci-onchain-census-contract/lib/davinci-contracts/",
  "davinci-onchain-census-contract/=lib/davinci-onchain-census-contract/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
